# Generated by Django 4.1.3 on 2022-11-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'gallery'},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
